export enum DrillActions {
  curve = "CURVE",
  draw = "DRAW",
  text = "TEXT",
  geometry = 'GEOMETRY',
  random = "RANDOM",
  delete = 'DELETE'
}

export enum CurveTypes {
  straightSkate = "STRAIGHT_SKATE",
  freeHandSkate = "FREEHAND_SKATE",
  straightSkateWithStop = "STRAIGHT_SKATE_WITH_STOP",
  freeHandSkateWithStop = "FREEHAND_SKATE_WITH_STOP",
  freeHandSkateWithPuck = "FREEHAND_SKATE_WITH_PUCK",
  freeHandSkateWithPuckAndStop = "FREEHAND_SKATE_WITH_PUCK_AND_STOP",
  freehandSkateBackwardWithPuckAndStop = "FREEHAND_SKATE_BACKWARD_WITH_PUCK_AND_STOP",
  freehandSkateBackwardWithPuck = "FREEHAND_SKATE_BACKWARD_WITH_PUCK",
  freehandSkateBackwardWithoutPuckAndStop = "FREEHAND_SKATE_BACKWARD_WITHOUT_PUCK_AND_STOP",
  freehandSkateBackwardWithoutPuck = "FREEHAND_SKATE_BACKWARD_WITHOUT_PUCK",
  straightPass = "STRAIGHT_PASS",
  straightShot = "STRAIGHT_SHOT",
  freehandLateralSkating = "FREEHAND_LATERAL_SKATING",
  freehandLateralSkatingToStop = "FREEHAND_LATERAL_SKATING_TO_STOP",
  puck = "PUCK",
  groupOfPucks = "GROUP_OF_PUCKS",
  zigzag = "ZIGZAG",
  curve = "CURVE",
  rectangle = "RECTANGLE",
  filledRectangle = "FILLED_RECTANGLE",
  circle = "CIRCLE",
  filledCircle = "FILLED_CIRCLE",
  triangle = "TRIANGLE",
  filledTriangle = "FILLED_TRIANGLE",
  starightLine = "STARIGHTLINE",
  freehandLine = "FREEHANDLINE",
  straightDashedLine = "STRAIGHT_DASHEDLINE",
  freehandDashedLine = "FREEHAND_DASHEDLINE",
}
